name = "primecare-api"
main = "src/index.ts"
compatibility_date = "2024-02-01"

[vars]
# DATABASE_URL = "" (Set via secrets)

[[r2_buckets]]
binding = "DOCS_BUCKET"
bucket_name = "primecare-docs"

[durable_objects]
bindings = [
  { name = "CHAT_SERVER", class_name = "ChatServer" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatServer"]
